### ISSUE TITLE
Pause current playing media on prayer time

### ISSUE THREAD

**Issue by mbaraa** [Prayer-Companion/PrayerCompanionAndroid#18]
It's like when a media is playing and another media starts the previous one pauses, or when a media is playing an the phone rings, the media pauses.

So if a media is being played, and a prayer's time is up, it is preferred that the companion pauses the media, and preferably an option to enable/disable it (for a better user experience).

**Comment by RaedGhazal** [comment]
Nice! That sounds like a great idea actually!
we can definitely consider this feature and plan it into our work

**Comment by RaedGhazal** [comment]
Thank you for your contribution!
